### PR TITLE
Remove Forwardable and release 0.2.5

### LINKED ISSUE #99: Delegating from form object causes `ArgumentError` with 0.2.4
I upgraded a Rails app that uses reform-rails from 0.2.3 to 0.2.4 today, and RSpec builds will no longer run due to an apparent delegation-related bug. The app in particular uses Ruby 3.1.2 and Rails 7.0.4.3. Pinning back to 0.2.3, these errors go away.

Example error:

```
An error occurred while loading ./spec/forms/create_collection_form_spec.rb.
Failure/Error: delegate :persisted?, :to_param, to: :collection

ArgumentError:
  wrong number of arguments (given 3, expected 1)
# ./app/forms/draft_collection_form.rb:97:in `<class:DraftCollectionForm>'
# ./app/forms/draft_collection_form.rb:4:in `<top (required)>'
# /media/mjg/44aee93d-a48a-4ad3-ae90-4b084bb04b69/rvm/gems/ruby-3.1.2@h2/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/k
ernel_require.rb:32:in `require'
# /media/mjg/44aee93d-a48a-4ad3-ae90-4b084bb04b69/rvm/gems/ruby-3.1.2@h2/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/k
ernel_require.rb:32:in `require'
# /media/mjg/44aee93d-a48a-4ad3-ae90-4b084bb04b69/rvm/gems/ruby-3.1.2@h2/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:30:in `require'
# ./app/forms/create_collection_form.rb:4:in `<top (required)>'
# /media/mjg/44aee93d-a48a-4ad3-ae90-4b084bb04b69/rvm/gems/ruby-3.1.2@h2/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/k
ernel_require.rb:32:in `require'
# /media/mjg/44aee93d-a48a-4ad3-ae90-4b084bb04b69/rvm/gems/ruby-3.1.2@h2/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/k
ernel_require.rb:32:in `require'
# /media/mjg/44aee93d-a48a-4ad3-ae90-4b084bb04b69/rvm/gems/ruby-3.1.2@h2/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:30:in `require'
# ./spec/forms/create_collection_form_spec.rb:5:in `<top (required)>'
```

Here's the form object in question: https://github.com/sul-dlss/happy-heron/blob/main/app/forms/draft_collection_form.rb#L97

### PR DESCRIPTION
**Pull request by richardboehme**
Fixes #99

### CODE REVIEW

File: lib/reform/form/active_model.rb [hunk 1]
```diff
@@ -4,8 +4,11 @@ def self.included(base)
       extend ClassMethods
       register_feature ActiveModel
 
-      extend Forwardable
-      def_delegators :model, :persisted?, :to_key, :to_param, :id
+      %i(persisted? to_key to_param id).each do |method|
+        define_method method do
+          model.public_send(method)
```
Comment (apotonick) [inline lib/reform/form/active_model.rb:9]: Can we not simply use https://www.rubydoc.info/gems/activesupport/Module:delegate as you suggested in the first place?

Comment (richardboehme) [reply lib/reform/form/active_model.rb]: You're right, I updated the code to use rails' `delegate` method instead.
